config/routes.rb
Auc::Application.routes.draw do
  resources :courses

  root :to => 'courses#index'

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  coursecode  :string(255)
#  description :string(255)
#  teacher     :string(255)
#  track       :string(255)
#  level       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  period_id   :integer
#  major_id    :integer
#

class Course < ActiveRecord::Base
  belongs_to :period
  belongs_to :major
  has_and_belongs_to_many(:prerequisites,
                          :join_table => "prerequisites",
                          :foreign_key => "course_a_id",
                          :association_foreign_key => "course_b_id",
                          :class_name => "Course")

  attr_accessible :coursecode, :description, :level, :major_id, :name, :teacher, :track, :period_id, :prerequisites, :prerequisite_ids
  validates :name, presence: true
  validates :teacher, presence: true


  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%").includes(:major, :period)
    else
      scoped
    end
  end
end

app/models/major.rb
# == Schema Information
#
# Table name: majors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Major < ActiveRecord::Base
  attr_accessible :name
end

app/models/period.rb
# == Schema Information
#
# Table name: periods
#
#  id         :integer          not null, primary key
#  offered_in :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Period < ActiveRecord::Base
  attr_accessible :period
end

app/models/prerequisite.rb
class Prerequisite < ActiveRecord::Base
  attr_accessible :course_a_id, :course_b_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
  	@course = Course.new
  end

  def create
    @course = Course.new(params[:course])
 
    if @course.save
      redirect_to :action => 'show', :id => @course.id
    else
       render :action => "new" 
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      redirect_to :action => 'show', :id => @course.id
    else
      render 'edit'
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def index
  if params[:term]
    @courses = Course.search(params[:term]).limit(10)
  elsif params[:id]
    @courses = Course.find(params[:id])
  else
    @courses = Course.all
  end

  respond_to do |format|  
    format.html 
    format.json { render :json => @courses.to_json(:include => [:major, :period, :prerequisites]) }
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courselist.html.erb
<% @courses.each do |course| %>
	<div class="course <%= course.major.name %> <%= course.period.offered_in %>" draggable="true">
		<ul>
		  <li><h5><%= course.name %></h5></li>
		  <li><%= course.major.name %> - <%= course.level %></li>
		  <li><%= course.period.offered_in %></li>
		</ul>
	</div>
<% end %>

app/views/courses/edit.html.erb
<div class="span6 offset2">
  <h1>Edit a course:</h1>
  <%= form_for(@course) do |f| %>
  <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :coursecode %>
    <%= f.text_field :coursecode %>

    <%= f.label :description %>
    <%= f.text_area :description, :rows => 3 %>

    <%= f.label :teacher %>
    <%= f.text_field :teacher %>

    <%= f.label :track %>
    <%= f.text_field :track %>

    <%= f.label :level %>
    <%= f.select(:level, options_for_select([[100,100],[200,200],[300,300]], @course.level)) %>

    <%= f.label :period %>
    <%= f.collection_select(:period_id, Period.all, :id, :offered_in) %>

    <%= f.label :major %>
    <%= f.collection_select(:major_id, Major.all, :id, :name) %>

    <%= f.label :prerequisite, "Prerequisites - Hold CTRL (cmd for Mac) to select multiple values" %>
    <%= f.collection_select(:prerequisite_ids, Course.all, :id, :name, {:selected => Prerequisite.where("course_a_id = ?", @course.id).pluck(:course_b_id)}, {:multiple => true}) %>


    <%= f.submit "Edit this course", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/courses/index.html.erb
<div id="wrapper">
  <div id="courses">
    <div>
      <%= form_tag courses_path, :method => 'get' do %>
        <div class="input-prepend">
          <span class="add-on"><i class='icon-search'></i></span>
          <%= search_field_tag :search,'', {:class => 'span2', :placeholder => "Enter a course name", :id =>"prependedInput"} %>       
        </div>
      <% end %>
    </div>

    <div class="courselist">
    </div>

    <figure class="bin">
      <img src="/assets/domo.png">  
      <figcaption>
        Recyle bin
      </figcaption>
    </figure>
  </div>

  <div id="curriculum">
  <table class="table table-bordered">
    <tr>
      <th class="rowhead"><a href="#" class="february" data-placement="bottom" data-title="Press here if you started in February. Watch out this erases the schedule!"><i class="icon-comment"></i></a></th>
      <th>Course 1</th>
      <th>Course 2</th>
      <th>Course 3</th>
      <th>Course 4 <i class="icon-plus"></i></th>
      <th style="display:none;" id="course5">Course 5 <i class="icon-remove-circle"></i></th>
      <th>Intensive period</th>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 6</p><p class="period">Spring</p></td>
      <td><div class="courseplace spring" id="y3s2c1"></div></td>
      <td><div class="courseplace spring" id="y3s2c2"></div></td>
      <td><div class="courseplace spring" id="y3s2c3"></div></td>
      <td><div class="courseplace spring" id="y3s2c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace spring" id="y3s2c5"></div></td>
      <td><div class="courseplace intensive-spring" id="y3in2"></div></td>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 5</p><p class="period">Fall</p></td>
      <td><div class="courseplace fall" id="y3s1c1"></div></td>
      <td><div class="courseplace fall" id="y3s1c2"></div></td>
      <td><div class="courseplace fall" id="y3s1c3"></div></td>
      <td><div class="courseplace fall" id="y3s1c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace fall" id="y3s1c5"></div></td>
      <td><div class="courseplace intensive-fall" id="y3in1"></div></td>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 4</p><p class="period">Spring</p></td>
      <td><div class="courseplace spring" id="y2s2c1"></div></td>
      <td><div class="courseplace spring" id="y2s2c2"></div></td>
      <td><div class="courseplace spring" id="y2s2c3"></div></td>
      <td><div class="courseplace spring" id="y2s2c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace spring" id="y2s2c5"></div></td>
      <td><div class="courseplace intensive-spring" id="y2in2"></div></td>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 3</p><p class="period">Fall</p></td>
      <td><div class="courseplace fall" id="y2s1c1"></div></td>
      <td><div class="courseplace fall" id="y2s1c2"></div></td>
      <td><div class="courseplace fall" id="y2s1c3"></div></td>
      <td><div class="courseplace fall" id="y2s1c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace fall" id="y2s1c5"></div></td>
      <td><div class="courseplace intensive-fall" id="y2in1"></div></td>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 2</p><p class="period">Spring</p></td>
      <td><div class="courseplace spring" id="y1s2c1"></div></td>
      <td><div class="courseplace spring" id="y1s2c2"></div></td>
      <td><div class="courseplace spring" id="y1s2c3"></div></td>
      <td><div class="courseplace spring" id="y1s2c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace spring" id="y1s2c5"></div></td>
      <td><div class="courseplace intensive-spring" id="y1in2"></div></td>
    </tr>
    <tr>
      <td class="rowhead"><p>Semester 1</p><p class="period">Fall</p></td>
      <td><div class="courseplace fall" id="y1s1c1"></div></td>
      <td><div class="courseplace fall" id="y1s1c2"></div></td>
      <td><div class="courseplace fall" id="y1s1c3"></div></td>
      <td><div class="courseplace fall" id="y1s1c4"></div></td>
      <td class="course5" style="display:none;"><div class="courseplace fall" id="y1s1c5"></div></td>
      <td><div class="courseplace intensive-fall" id="y1in1"></div></td>
    </tr>
  </table>
  </div>
</div>

<script>
$(function() {
 // Below is the name of the textfield that will be autocomplete    
    $('#prependedInput').autocomplete({
            minLength: 2,
            source: '<%= courses_path(:json) %>',
            focus: function(event, ui) {
                $('#prependedInput').val(ui.item.name);
                return false;
            },
 // Once a value in the drop down list is selected, do the following:
            select: function(event, ui) {
 // place the person.given_name value into the textfield called 'select_origin'...
 //Should put this stuff directly into the table, first possible place
                $('#prependedInput').val('');

                var prerequisites = [];

                $.each(ui.item.prerequisites, function(){
                    prerequisites.push(this.id);
                });

                var course = {
                  'major' :  ui.item.major.name, 
                  'period' : ui.item.period.offered_in, 
                  'id' : ui.item.id,
                  'level' : ui.item.level,
                  'name' : ui.item.name,
                  'prerequisites' : prerequisites
                };

                if (course.period.indexOf('intensive') >= 0){
                   var placeId = findintensiveplace(localStorage['start'], course.period, 1, 1);
                 } else {
                  var placeId = findplace(localStorage['start'], course.period, 1, 1, 1);
                 }

                if (placeId != undefined){
                  localStorage.setItem(placeId,JSON.stringify(course));
                  storagetodiv(placeId);

                  for (var i = 0; i < localStorage.length; i++){
                    id = localStorage.key(i);
                    if (id != 'start')
                      checkprereq(id);
                   }
                }
                return false;
            }

        })
 // The below code is straight from the jQuery example. It formats what data is displayed in the dropdown box, and can be customized.
        .data( "autocomplete" )._renderItem = function( ul, item ) {
            return $( "<li></li>" )
                .data( "item.autocomplete", item )
 // For now which just want to show the person.given_name in the list.
                .append( "<a>" + item.name + "</a>" )
                .appendTo( ul );
        };
});
</script>

app/views/courses/new.html.erb
<h1>Create a course:</h1>

<div class="row">
  <div class="span6 offset5">
    <%= form_for(@course) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :course_name %>
      <%= f.text_field :name %>

      <%= f.label :course_code %>
      <%= f.text_field :coursecode %>

      <%= f.label :description %>
      <%= f.text_area :description, :rows => 3 %>

      <%= f.label :teacher %>
      <%= f.text_field :teacher %>

      <%= f.label :track %>
      <%= f.text_field :track %>

      <%= f.label :level %>
      <%= f.select(:level, options_for_select([[100,100],[200,200],[300,300]])) %>

      <%= f.label :period %>
      <%= f.collection_select(:period_id, Period.all, :id, :offered_in) %>

      <%= f.label :major %>
      <%= f.collection_select(:major_id, Major.all, :id, :name) %>

      <%= f.label :prerequisite, "Prerequisites - Hold CTRL (cmd for Mac) to select multiple values" %>
      <%= f.collection_select(:prerequisite_ids, Course.all, :id, :name, {}, {:multiple => true}) %>

      <%= f.submit "Create this course", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

app/views/courses/show.html.erb
<div class="span8 offset2">
	<h1><%= @course.name %></h1>
	<table class ="table">
		<tbody>
			<tr>
				<td>Course:</td>
				<td><%= @course.name %> </td>
			</tr>
			<tr>
				<td>Course code:</td>
				<td><%= @course.coursecode %></td>
			</tr>
			<tr>
				<td>Course description:</td>
				<td><%= @course.description %></td>
			</tr>
			<tr>
				<td>Teacher:</td>
				<td><%= @course.teacher %></td>
			</tr>
			<tr>
				<td>Track:</td>
				<td><%= @course.track %></td>
			</tr>
			<tr>
				<td>Level:</td>
				<td><%= @course.level %></td>
			</tr>
			<tr>
				<td>Period:</td>
				<td><%= @course.period.offered_in %></td>
			</tr>
			<tr>
				<td>Major:</td>
				<td><%= @course.major.name %></td>
			</tr>
			<tr>
				<td>Prerequisites:</td>
				<td><%= @course.prerequisites.map(&:name).join(", ") %></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AUC curriculum builder</title>
    <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js" %>
    <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div id="logo">
        	AUC Curriculum builder!
        </div>
      </div>
    </header>
      <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @course.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@course.errors.count, "error") %>.
    </div>
    <ul>
    <% @course.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>